from __future__ import annotations

US_SEED = [
    'SPY','QQQ','IWM','RSP','TLT','HYG','UUP','EEM','^VIX','XLE','XLF','XLI','XLB','XLK','XLV','XLY','XLP','XLU','XLRE','XLC',
    'VUG','VTV','QUAL','MTUM','USMV','SPHB','IWD','IWF','AAPL','MSFT','NVDA','AMZN','META','GOOGL','TSLA','AVGO','AMD','NFLX','ORCL',
    'CRM','NOW','ADBE','INTU','PANW','ANET','AMAT','MU','QCOM','TXN','INTC','JPM','BAC','WFC','GS','MS','BLK','KKR','BX','SCHW',
    'HOOD','COIN','V','MA','PYPL','XOM','CVX','COP','SLB','HAL','BKR','OXY','DVN','EOG','KMI','WMB','OKE','FCX','NEM','GOLD',
    'CAT','DE','GE','LMT','NOC','RTX','BA','UNP','CSX','NSC','LLY','UNH','JNJ','MRK','ABBV','PFE','ISRG','ABT','TMO','MDT',
    'WMT','COST','PG','KO','PEP','MCD','UBER','BKNG','CMG','HD','LOW','TGT','NKE','DIS','ROST','TJX','ETSY','LEN','DHI','PHM',
    'PLTR','SMCI','MSTR','SNOW','SHOP','SQ','AFRM','TTD','RDDT','ARM','ASML','KLAC','LRCX','CDNS','SNPS'
]

IHSG_SEED = [
    'BBCA.JK','BBRI.JK','BMRI.JK','BBNI.JK','TLKM.JK','ASII.JK','BRIS.JK','BNGA.JK','BBTN.JK','BTPS.JK','NISP.JK','MEGA.JK',
    'ADRO.JK','PTBA.JK','ITMG.JK','HRUM.JK','INDY.JK','AADI.JK','UNTR.JK','BUMI.JK','PGEO.JK','MEDC.JK','AKRA.JK',
    'ANTM.JK','INCO.JK','MDKA.JK','TINS.JK','BRMS.JK','DKFT.JK','ICBP.JK','INDF.JK','MYOR.JK','KLBF.JK','SIDO.JK','CMRY.JK','ULTJ.JK',
    'AMRT.JK','ACES.JK','MAPI.JK','ERAA.JK','JSMR.JK','PGAS.JK','EXCL.JK','ISAT.JK','WIKA.JK','PTPP.JK','ADHI.JK','SMDR.JK','TMAS.JK',
    'CTRA.JK','BSDE.JK','PWON.JK','SMRA.JK','HEAL.JK','MIKA.JK','SILO.JK','CPIN.JK','JPFA.JK','INKP.JK','TKIM.JK','ESSA.JK','AALI.JK','LSIP.JK','MAPA.JK','AUTO.JK'
]

FOREX_SEED = ['EURUSD=X','GBPUSD=X','AUDUSD=X','NZDUSD=X','JPY=X','CHF=X','CAD=X','EURJPY=X','GBPJPY=X','AUDJPY=X','NZDJPY=X','EURGBP=X','EURCHF=X','IDR=X','CNH=X','SGD=X']

COMMODITIES_SEED = ['GC=F','SI=F','CL=F']

CRYPTO_SEED = [
    'BTC-USD','ETH-USD','SOL-USD','BNB-USD','XRP-USD','ADA-USD','AVAX-USD','LINK-USD','DOT-USD','DOGE-USD',
    'ATOM-USD','NEAR-USD','APT-USD','ARB-USD','OP-USD','MATIC-USD','SUI20947-USD','AAVE-USD','UNI7083-USD','MKR-USD','LDO-USD','CRV-USD','COMP5692-USD',
    'FET-USD','TAO22974-USD','RNDR-USD','RENDER-USD','GRT6719-USD','ONDO-USD','POLYX-USD','TON11419-USD','INJ-USD','SEI-USD','TIA22861-USD','PYTH-USD',
    'WIF-USD','PEPE24478-USD','BONK-USD','FLOKI-USD','BRETT-USD'
]

MARKET_SEEDS = {
    'us': US_SEED,
    'ihsg': IHSG_SEED,
    'forex': FOREX_SEED,
    'commodities': COMMODITIES_SEED,
    'crypto': CRYPTO_SEED,
}
