from __future__ import annotations
from config.data_symbol_map import DATA_TO_DISPLAY
DISPLAY_NAME_MAP = {"^JKSE":"IHSG","^VIX":"VIX"}
for sym in ["BBCA.JK","BBRI.JK","BMRI.JK","BBNI.JK","TLKM.JK","ASII.JK","BRIS.JK","BNGA.JK","BBTN.JK","BTPS.JK","NISP.JK","MEGA.JK","AADI.JK","ADRO.JK","PTBA.JK","ITMG.JK","HRUM.JK","INDY.JK","UNTR.JK","BUMI.JK","PGEO.JK","MEDC.JK","AKRA.JK","ANTM.JK","INCO.JK","MDKA.JK","TINS.JK","BRMS.JK","DKFT.JK","ICBP.JK","INDF.JK","MYOR.JK","KLBF.JK","SIDO.JK","CMRY.JK","ULTJ.JK","AMRT.JK","ACES.JK","MAPI.JK","ERAA.JK","JSMR.JK","PGAS.JK","EXCL.JK","ISAT.JK","WIKA.JK","PTPP.JK","ADHI.JK","SMDR.JK","TMAS.JK","CTRA.JK","BSDE.JK","PWON.JK","SMRA.JK","HEAL.JK","MIKA.JK","SILO.JK","CPIN.JK","JPFA.JK","INKP.JK","TKIM.JK","ESSA.JK","AALI.JK","LSIP.JK","MAPA.JK","AUTO.JK"]: DISPLAY_NAME_MAP[sym]=sym.replace('.JK','')
DISPLAY_NAME_MAP.update(DATA_TO_DISPLAY)
